### ISSUE TITLE
RIS has no objects label

### ISSUE THREAD

**Issue by HuYuzhang** [lsy17096535/Single-Image-Deraining#10]
Thank you for providing your datasets. But I find that the BaiduYun access of RIS provides only the images without label (ris.zip). And the GoogleDrive's link says I can not access the file. So can you provide the RIS's label? Thank you again!

**Comment by panda-lab** [comment]
you can get label from https://drive.google.com/drive/folders/1fwudnpjfCcGRBYp84nmnXZbhaPe3IfCP
