### ISSUE TITLE
A Question About the Article

### ISSUE THREAD

**Issue by bernardshen** [lsy17096535/Single-Image-Deraining#2]
In Section 3.3 you said that RID's rain effect is closest to "raindrops" and that of RIS's is closest to "rain and mist". But in section 4.3 you said that you used algorithm trained for rain and mist case for RID and use raindrop case for RIS. Is this a mistake in writing? Or dose this lead to the unsatisfactory result in section 4.3?

**Comment by panda-lab** [comment]
Thanks for pointing out this issues. 
This is a typo in our paper, we are sorry about this. In the experiments, we use the trained model on synthetic rain streak and raindrop images to test the RID dataset, and use the trained model on synthetic rain streak and mist images to test the RIS dataset. All the results reported in the paper are based on the protocol.
