### ISSUE TITLE
Synthetic rain streak dataset

### ISSUE THREAD

**Issue by hkzhang-git** [lsy17096535/Single-Image-Deraining#5]
Thanks for your good job at first. From your paper, I learned that the synthetic rain streak dataset should has 2400 pairs images for training, and 200 pairs images for testing. But, the synthetic rain streak dataset that download from your link https://pan.baidu.com/s/11t4XIx6f3CEvmOw2XO9fqQ#list/path=%2F has more than 30k pairs images. Could you tell me which parts are used for training and testing ? thanks very much

**Comment by proteus1991** [comment]
I have the same question.

**Comment by panda-lab** [comment]
We synthetise more than 30k pairs image and release all the synthetic. We will check again and release the data some as paper.
